
function pre_filter1_config(this_block)

  % Revision History:
  %
  %   21-May-2016  (23:58 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/casrm/hcng_nov_m2/fpt_classifier/dropletdet_full/untouched/packer_files/pre_filter.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('pre_filter1');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('reset');
  this_block.addSimulinkInport('packer_len');
  this_block.addSimulinkInport('enable');
  this_block.addSimulinkInport('blk_rdy');

  this_block.addSimulinkOutport('fifo_wr1');
  this_block.addSimulinkOutport('fifo_wr2');
  this_block.addSimulinkOutport('fifo_wr3');
  this_block.addSimulinkOutport('fifo_wr4');

  fifo_wr1_port = this_block.port('fifo_wr1');
  fifo_wr1_port.setType('UFix_1_0');
  fifo_wr1_port.useHDLVector(false);
  fifo_wr2_port = this_block.port('fifo_wr2');
  fifo_wr2_port.setType('UFix_1_0');
  fifo_wr2_port.useHDLVector(false);
  fifo_wr3_port = this_block.port('fifo_wr3');
  fifo_wr3_port.setType('UFix_1_0');
  fifo_wr3_port.useHDLVector(false);
  fifo_wr4_port = this_block.port('fifo_wr4');
  fifo_wr4_port.setType('UFix_1_0');
  fifo_wr4_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('reset').width ~= 1);
      this_block.setError('Input data type for port "reset" must have width=1.');
    end

    this_block.port('reset').useHDLVector(false);

    if (this_block.port('packer_len').width ~= 13);
      this_block.setError('Input data type for port "packer_len" must have width=13.');
    end

    if (this_block.port('enable').width ~= 1);
      this_block.setError('Input data type for port "enable" must have width=1.');
    end

    this_block.port('enable').useHDLVector(false);

    if (this_block.port('blk_rdy').width ~= 1);
      this_block.setError('Input data type for port "blk_rdy" must have width=1.');
    end

    this_block.port('blk_rdy').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('untouched/packer_files/pre_filter.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

